### ISSUE TITLE
Component Request: Toggle Button

### ISSUE THREAD

**Issue by e-hamza** [Drawless/drawless#6]
**Please describe the component**
A toggle button that contains a boolean value (enabled, disabled). For example to be used in the user's settings.

**UI Design example (optional)**
![image](https://github.com/Drawless/drawless/assets/32574974/13b6ec46-d7cd-4cf7-a6e5-2f229fc8ac48)

Thanks

**Comment by e-hamza** [comment]
@annouri, would you be interested in implementing this? 😏

**Comment by annouri** [comment]
@e-hamza yes of course 😎

**Comment by e-hamza** [comment]
@annouri thanks!

**Comment by annouri** [comment]
@e-hamza Toggle Button created here  #16 😃
